-- MySQL dump generated from SQLite database: sql-learn.db
-- Generated by script/sqlite-to-mysql.py

CREATE DATABASE IF NOT EXISTS `sql_learn` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `sql_learn`;
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `departments`;
CREATE TABLE `departments` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(255) NOT NULL,
  `budget` DECIMAL(10,2)
);

DROP TABLE IF EXISTS `categories`;
CREATE TABLE `categories` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS `customers`;
CREATE TABLE `customers` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) UNIQUE,
  `city` VARCHAR(255),
  `join_date` DATE
);

DROP TABLE IF EXISTS `employees`;
CREATE TABLE `employees` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) UNIQUE,
  `department_id` INT REFERENCES `departments`(`id`),
  `hire_date` DATE,
  `salary` DECIMAL(10,2),
  `manager_id` INT REFERENCES `employees`(`id`)
);

DROP TABLE IF EXISTS `suppliers`;
CREATE TABLE `suppliers` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) UNIQUE,
  `city` VARCHAR(255),
  `country` VARCHAR(255) DEFAULT 'USA',
  `rating` DECIMAL(10,2) DEFAULT 3.0,
  `is_active` TINYINT(1) DEFAULT 1,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS `promotions`;
CREATE TABLE `promotions` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `code` VARCHAR(255) UNIQUE NOT NULL,
  `discount_percent` DECIMAL(10,2) NOT NULL,
  `min_purchase` DECIMAL(10,2) DEFAULT 0,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  `max_uses` INT DEFAULT 100,
  `is_active` TINYINT(1) DEFAULT 1
);

DROP TABLE IF EXISTS `products`;
CREATE TABLE `products` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(255) NOT NULL,
  `category_id` INT REFERENCES `categories`(`id`),
  `price` DECIMAL(10,2) NOT NULL,
  `stock` INT DEFAULT 0
);

DROP TABLE IF EXISTS `orders`;
CREATE TABLE `orders` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `customer_id` INT REFERENCES `customers`(`id`),
  `order_date` DATE,
  `status` VARCHAR(255) DEFAULT 'pending',
  `total` DECIMAL(10,2),
  `promotion_id` INT REFERENCES `promotions`(`id`)
);

DROP TABLE IF EXISTS `order_items`;
CREATE TABLE `order_items` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `order_id` INT REFERENCES `orders`(`id`),
  `product_id` INT REFERENCES `products`(`id`),
  `quantity` INT DEFAULT 1,
  `price` DECIMAL(10,2) NOT NULL
);

DROP TABLE IF EXISTS `shipments`;
CREATE TABLE `shipments` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `order_id` INT REFERENCES `orders`(`id`),
  `supplier_id` INT REFERENCES `suppliers`(`id`),
  `shipment_date` DATE,
  `delivery_date` DATE,
  `tracking_number` VARCHAR(255),
  `status` VARCHAR(255) DEFAULT 'pending' CHECK (status IN ('pending', 'shipped', 'delivered', 'returned', 'cancelled'))
);

DROP TABLE IF EXISTS `product_reviews`;
CREATE TABLE `product_reviews` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `product_id` INT REFERENCES `products`(`id`),
  `customer_id` INT REFERENCES `customers`(`id`),
  `rating` INT CHECK (rating >= 1 AND rating <= 5),
  `review_text` TEXT,
  `review_date` DATETIME DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS `gift_cards`;
CREATE TABLE `gift_cards` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `code` VARCHAR(255) UNIQUE NOT NULL,
  `customer_id` INT REFERENCES `customers`(`id`),
  `initial_amount` DECIMAL(10,2) NOT NULL,
  `current_balance` DECIMAL(10,2) NOT NULL,
  `issue_date` DATE NOT NULL,
  `expiration_date` DATE,
  `is_redeemed` TINYINT(1) DEFAULT 0
);

-- Data

INSERT INTO `departments` (`id`, `name`, `budget`) VALUES
('1', 'Sales', '50000.0'),
('2', 'Marketing', '30000.0'),
('3', 'IT', '45000.0'),
('4', 'HR', '25000.0'),
('5', 'Finance', '35000.0');

INSERT INTO `categories` (`id`, `name`) VALUES
('1', 'Electronics'),
('2', 'Clothing'),
('3', 'Books'),
('4', 'Home & Garden'),
('5', 'Sports');

INSERT INTO `customers` (`id`, `name`, `email`, `city`, `join_date`) VALUES
('1', 'John Doe', 'john.doe@email.com', 'New York', '2023-01-10'),
('2', 'Jane Smith', 'jane.smith@email.com', 'Los Angeles', '2023-02-15'),
('3', 'Mike Johnson', 'mike.j@email.com', 'Chicago', '2023-03-20'),
('4', 'Sarah Brown', 'sarah.b@email.com', 'New York', '2023-04-05'),
('5', 'Tom Wilson', 'tom.w@email.com', 'Houston', '2023-05-12'),
('6', 'Lisa Garcia', 'lisa.g@email.com', 'Phoenix', '2023-06-18'),
('7', 'Kevin Martinez', 'kevin.m@email.com', 'Chicago', '2023-07-22'),
('8', 'Emma Davis', 'emma.d@email.com', 'Seattle', '2023-09-15');

INSERT INTO `employees` (`id`, `name`, `email`, `department_id`, `hire_date`, `salary`, `manager_id`) VALUES
('1', 'Alice Johnson', 'alice@company.com', '1', '2022-01-15', '5500.0', NULL),
('2', 'Bob Smith', 'bob@company.com', '1', '2021-06-20', '4800.0', '1'),
('3', 'Carol White', 'carol@company.com', '2', '2023-03-10', '5200.0', '6'),
('4', 'David Brown', 'david@company.com', '3', '2020-11-05', '7000.0', NULL),
('5', 'Eve Davis', 'eve@company.com', '4', '2022-08-30', '4500.0', '8'),
('6', 'Frank Miller', 'frank@company.com', '3', '2021-02-14', '6500.0', '4'),
('7', 'Grace Lee', 'grace@company.com', '2', '2023-01-20', '4900.0', NULL),
('8', 'Henry Wilson', 'henry@company.com', '1', '2022-07-08', '5100.0', '1');

INSERT INTO `suppliers` (`id`, `name`, `email`, `city`, `country`, `rating`, `is_active`, `created_at`) VALUES
('1', 'Tech Supply Co', 'orders@techsupply.com', 'San Francisco', 'USA', '4.5', '1', '2026-06-30 03:26:51'),
('2', 'Fashion Wholesale', 'sales@fashionwholesale.com', 'Los Angeles', 'USA', '4.2', '1', '2026-06-30 03:26:51'),
('3', 'Book Distributors Inc', 'contact@bookdist.com', 'New York', 'USA', '4.8', '1', '2026-06-30 03:26:51'),
('4', 'Garden Goods Ltd', 'info@gardengoods.com', 'Seattle', 'USA', '3.9', '1', '2026-06-30 03:26:51'),
('5', 'Sports Unlimited', 'orders@sportsunlim.com', 'Denver', 'USA', '4.1', '1', '2026-06-30 03:26:51');

INSERT INTO `promotions` (`id`, `code`, `discount_percent`, `min_purchase`, `start_date`, `end_date`, `max_uses`, `is_active`) VALUES
('1', 'SAVE10', '10.0', '50.0', '2024-01-01', '2024-12-31', '500', '1'),
('2', 'SAVE20', '20.0', '100.0', '2024-01-01', '2024-12-31', '300', '1'),
('3', 'SUMMER25', '25.0', '75.0', '2024-06-01', '2024-08-31', '200', '1'),
('4', 'FLASH50', '50.0', '200.0', '2024-04-01', '2024-04-30', '50', '1'),
('5', 'EXPIRED99', '15.0', '0.0', '2023-01-01', '2023-12-31', '100', '0');

INSERT INTO `products` (`id`, `name`, `category_id`, `price`, `stock`) VALUES
('1', 'Laptop', '1', '999.99', '50'),
('2', 'Smartphone', '1', '699.99', '100'),
('3', 'Headphones', '1', '149.99', '200'),
('4', 'T-Shirt', '2', '29.99', '500'),
('5', 'Jeans', '2', '59.99', '300'),
('6', 'Jacket', '2', '89.99', '150'),
('7', 'SQL Mastery', '3', '49.99', '80'),
('8', 'Python Guide', '3', '39.99', '120'),
('9', 'Garden Tools Set', '4', '79.99', '40'),
('10', 'Running Shoes', '5', '119.99', '75'),
('11', 'Basketball', '5', '34.99', '200'),
('12', 'Yoga Mat', '5', '24.99', '150');

INSERT INTO `orders` (`id`, `customer_id`, `order_date`, `status`, `total`, `promotion_id`) VALUES
('1', '1', '2024-01-15', 'completed', '1049.98', '1'),
('2', '2', '2024-01-18', 'completed', '749.98', '1'),
('3', '3', '2024-02-20', 'completed', '89.98', NULL),
('4', '1', '2024-02-28', 'completed', '149.99', NULL),
('5', '4', '2024-03-05', 'pending', '999.99', '2'),
('6', '5', '2024-03-10', 'shipped', '179.98', '2'),
('7', '2', '2024-03-15', 'completed', '49.99', '3'),
('8', '6', '2024-03-20', 'cancelled', '119.99', NULL),
('9', '7', '2024-04-01', 'completed', '198.97', '4'),
('10', '8', '2024-04-05', 'shipped', '89.98', NULL),
('11', '3', '2024-04-10', 'completed', '59.99', NULL),
('12', '5', '2024-04-15', 'completed', '154.98', NULL);

INSERT INTO `order_items` (`id`, `order_id`, `product_id`, `quantity`, `price`) VALUES
('1', '1', '1', '1', '999.99'),
('2', '1', '3', '1', '149.99'),
('3', '2', '2', '1', '699.99'),
('4', '3', '4', '2', '29.99'),
('5', '3', '5', '1', '59.99'),
('6', '4', '3', '1', '149.99'),
('7', '5', '1', '1', '999.99'),
('8', '6', '10', '1', '119.99'),
('9', '6', '12', '1', '24.99'),
('10', '6', '11', '1', '34.99'),
('11', '7', '7', '1', '49.99'),
('12', '8', '10', '1', '119.99'),
('13', '9', '3', '1', '149.99'),
('14', '9', '6', '1', '89.99'),
('15', '9', '8', '1', '39.99'),
('16', '10', '4', '2', '29.99'),
('17', '10', '5', '1', '59.99'),
('18', '11', '5', '1', '59.99'),
('19', '12', '9', '1', '79.99'),
('20', '12', '12', '3', '24.99');

INSERT INTO `shipments` (`id`, `order_id`, `supplier_id`, `shipment_date`, `delivery_date`, `tracking_number`, `status`) VALUES
('1', '1', '1', '2024-01-16', '2024-01-18', 'SHIP001', 'delivered'),
('2', '2', '1', '2024-01-19', '2024-01-22', 'SHIP002', 'delivered'),
('3', '3', '2', '2024-02-21', '2024-02-24', 'SHIP003', 'delivered'),
('4', '5', '1', '2024-03-06', NULL, 'SHIP004', 'shipped'),
('5', '6', '4', '2024-03-11', NULL, 'SHIP005', 'shipped'),
('6', '7', '2', '2024-03-16', '2024-03-19', 'SHIP006', 'delivered');

INSERT INTO `product_reviews` (`id`, `product_id`, `customer_id`, `rating`, `review_text`, `review_date`) VALUES
('1', '1', '1', '5', 'Excellent laptop! Fast processor and beautiful display.', '2024-02-01'),
('2', '1', '2', '4', 'Good laptop but a bit pricey for the specs.', '2024-02-10'),
('3', '3', '1', '5', 'Amazing sound quality! Best headphones I have owned.', '2024-02-15'),
('4', '4', '3', '4', 'Nice soft cotton t-shirt. Good value for money.', '2024-03-01'),
('5', '7', '4', '5', 'Must read for anyone learning SQL! Clear and practical.', '2024-03-15'),
('6', '10', '5', '4', 'Comfortable running shoes. Great arch support.', '2024-04-01');

INSERT INTO `gift_cards` (`id`, `code`, `customer_id`, `initial_amount`, `current_balance`, `issue_date`, `expiration_date`, `is_redeemed`) VALUES
('1', 'GC100', '1', '100.0', '0.0', '2024-01-01', '2025-01-01', '1'),
('2', 'GC200', '1', '50.0', '35.5', '2024-02-15', '2025-02-15', '1'),
('3', 'GC300', '2', '75.0', '75.0', '2024-03-01', '2025-03-01', '0'),
('4', 'GC400', NULL, '25.0', '25.0', '2024-03-10', '2025-03-10', '0'),
('5', 'GC500', NULL, '100.0', '100.0', '2024-04-01', '2025-04-01', '0');

SET FOREIGN_KEY_CHECKS=1;
